version: '3.7'
services:
  php_acc:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - mysql_acc
    container_name: php_acc_container

  mysql_acc:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=accounting
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password2019
    ports:
      - 33060:3306
    container_name: mysql_acc_container

  phpmyadmin_acc:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_acc_container
    ports:
      - 9999:80
    links:
      - mysql_acc:db